name: SimpleCheck
version: '${project.version}'
main: com.pashmash.simplecheck.SimpleCheck
api-version: '1.20'
authors:
  - PashMash
  - DrecksOsiLand
commands:
  check:
    description: check a player
    usage: /check <player>
